### ISSUE TITLE
Post 모델에 좋아요 기능 추가.

### ISSUE THREAD

**Issue by nacyot** [dev-study-ghost/mission#13]

**Comment by meoooh** [comment]
좋아요 기능 구현에 대한 논의 합니다...

좋아요 기능이라는게,

하나의 Post가 여러 User에게 좋아요를 당할(?) 수 있고,

하나의 User가 여러 Post를 좋아요 할수 있는데...

이때... 어떤걸로 관계를 맺어야 하나요...;;

어렵네요... ㅠㅠ

**Comment by meoooh** [comment]
어떻게 보면 서로 has_many인데...

**Comment by nacyot** [comment]
둘 다 has_and_belongs_to_many 를 써야합니다.  

http://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association

요샌 저 키워드를 직접 쓰긴 보다 through 옵션을 사용하는 게 정석 인 듯 합니다만. 두 예제 다 포함되어 있습니다.

**Comment by meoooh** [comment]
이럴땐 어떻게 하나요..;;

``` ruby
class User < ActiveRecord::Base
  has_many :comments
  has_many :posts #이건 post랑 belongs_to로 연결한거...
  has_many :likeposts
  has_many :posts, through: :likeposts #여긴 like기능때문에 구현한거...
end
```

긍까 문제는 같은 테이블끼리 중복으로 연결(?)할때인데...;;

posts가 중복되는데...

**Comment by nacyot** [comment]
has_many :posts, through: :likeposts 는 user 모델에 있을 필요가 없어보입니다.

이 부분은 like 모델에 있어야 할 거 같은데요.

**Comment by meoooh** [comment]
like모델이라면

http://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many

이 예제에서는 

manifests를 말씀하시는건가요??

**Comment by nacyot** [comment]
제가 착각했네요. 고민해봐야할 듯 합니다. 추가하겠습니다.

**Comment by nacyot** [comment]
``` ruby
class User < ActiveRecord::Base
  has_many :comments
  has_many :posts #이건 post랑 belongs_to로 연결한거...
  has_many :likeposts
  has_many :liked_posts, through: :likeposts, source: :post 
  #has_many :posts, through: :likeposts #여긴 like기능때문에 구현한거...
end
```

이런 식으로 하면 될 것 같습니다.

**Comment by meoooh** [comment]
source는 뭔가요?

**Comment by meoooh** [comment]
http://stackoverflow.com/a/4632472 이거군요!!!

**Comment by nacyot** [comment]
넵 ㅎㅎ

http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many

api 문서인데 옵션이 너무 많아서 당황스럽네요 ㅋㅋ

**Comment by meoooh** [comment]
라이크기능 쉽게 봤는데.... 후... 어렵네요...

**Comment by meoooh** [comment]
주석 달린 커밋: https://github.com/dev-study-ghost/mission/commit/3cef5899461e846829c544c52c826642095cea13
