### ISSUE TITLE
Post 모델 create시 user_id도 설정하기

### ISSUE THREAD

**Issue by meoooh** [dev-study-ghost/mission#17]
Post 모델 create시 user_id도 설정하기

**Comment by meoooh** [comment]
이 이슈 처리하려면...

음...

devise로 로그인 성공했을때

sessions[:id] = @user

뭐 이런식으로 session에 user정보를 넣어야되는데 어떻게 해야할지 모르겠네요...

일단 로그인 성공시 실행되는 컨트롤러를 못찾겠어요...;;

**Comment by nacyot** [comment]
Devise에서 지원합니다. 현재 로그인된 user을 나타내는 current_user를 사용할 수 있습니다. 그 외에 로그인 여부를 확인하는 편의 메소드인  signed_in? (확인이 필요합니다) 같은 것도 사용할 수 있습니다.

**Comment by meoooh** [comment]
그럼 post나 comment 컨트롤러에서

@user = current_user

저렇게 하면

@user에 현재 로그인한 사용자 객체(?)가 들어가는거에요?

**Comment by nacyot** [comment]
네 아마 그렇게 사용 가능할 것 같습니다. 근데 그렇게 하면 로그인 안 돼있을 때 어떻게 될지 모르겠네요. 에러가 날 듯 싶은데. 테스트해보고 궁리해봐야겠네요.

**Comment by meoooh** [comment]
해보고 피드백 드릴게요

**Comment by meoooh** [comment]
말씀하신대로 current_user 가능하네요~

**Comment by frozenrainyoo** [comment]
아래처럼 하면 되겟네요? 맞나요?

 app/controllers/posts_controller.rb
   def create
     @post = Post.new(post_params)
     @post.user = current_user

**Comment by meoooh** [comment]
네 그렇게 하면 될껍니다...!

**Comment by meoooh** [comment]
그런데 다만 그렇게 했을때는 꼭 마지막에

@post.save를 해줘야 할겁니다... 그래야 반영되는걸로 알고있습니다.

대신 update_attribute를 쓰면 자동저장됩니다.
